"""Forge CLI skeleton for Alfa automation."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List

from .selector import filter_records
from .template_engine import TemplateEngineError, render_template

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "forge.config.json"
LOG_PATH = ROOT / "logs" / "forge.log"


def load_config() -> Dict[str, Any]:
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Missing forge config at {CONFIG_PATH}")
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def write_log(event: str, payload: Dict[str, Any]) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "event": event,
        **payload,
    }
    with LOG_PATH.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(entry, ensure_ascii=False) + "\n")


def ensure_alfa_root(config: Dict[str, Any]) -> Path:
    alfa_root = ROOT / config.get("alfa_root", "alfas/")
    alfa_root.mkdir(parents=True, exist_ok=True)
    return alfa_root


def list_alfa_records(alfa_root: Path) -> List[Dict[str, Any]]:
    records: List[Dict[str, Any]] = []
    for manifest_path in alfa_root.glob("*/manifest.json"):
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        record = {
            "id": manifest.get("id") or manifest_path.parent.name,
            "realm": manifest.get("realm"),
            "entropy": manifest.get("entropy_index"),
            "path": str(manifest_path.parent),
            "manifest_path": str(manifest_path),
            "manifest": manifest,
        }
        records.append(record)
    return records


def apply_selector(records: Iterable[Dict[str, Any]], expression: str) -> List[Dict[str, Any]]:
    if not expression:
        return list(records)
    return filter_records(records, expression)


def command_init_alfa(args: argparse.Namespace) -> int:
    config = load_config()
    alfa_root = ensure_alfa_root(config)
    alfa_id = args.id
    alfa_dir = alfa_root / alfa_id
    if alfa_dir.exists() and not args.force:
        print(f"[forge] Alfa {alfa_id} already exists at {alfa_dir}", file=sys.stderr)
        return 1
    alfa_dir.mkdir(parents=True, exist_ok=True)

    context = {
        "alfa_id": alfa_id,
        "realm": args.realm,
        "entropy_index": args.entropy,
        "template_version": config.get("default_template_version", "forge-template@1.0.0"),
    }

    try:
        manifest_content = render_template("alfa/manifest.json.j2", context)
        core_content = render_template("alfa/alfa.py.j2", context)
    except TemplateEngineError as exc:
        print(f"[forge] template error: {exc}", file=sys.stderr)
        return 1

    (alfa_dir / "manifest.json").write_text(manifest_content, encoding="utf-8")
    (alfa_dir / "alfa.py").write_text(core_content, encoding="utf-8")
    (alfa_dir / "README.md").write_text(
        f"# {alfa_id}\n\nGenerated by Forge using template version {context['template_version']}.\n",
        encoding="utf-8",
    )

    ranks_created: list[str] = []
    for rank_name in args.activate_rank:
        template_path = f"ranks/{rank_name}.json.j2"
        output_path = alfa_dir / f"{rank_name}.json"
        try:
            rendered_rank = render_template(template_path, context)
        except TemplateEngineError as exc:
            print(f"[forge] template error for rank '{rank_name}': {exc}", file=sys.stderr)
            return 1
        output_path.write_text(rendered_rank, encoding="utf-8")
        ranks_created.append(rank_name)

    manifest_data = json.loads(manifest_content)
    for rank_name in ranks_created:
        manifest_data.setdefault("ranks", {})[rank_name] = "ok"
    (alfa_dir / "manifest.json").write_text(json.dumps(manifest_data, indent=2) + "\n", encoding="utf-8")

    write_log(
        "init_alfa",
        {
            "alfa_id": alfa_id,
            "path": str(alfa_dir),
            "force": args.force,
            "ranks_created": ranks_created,
        },
    )
    print(f"[forge] Initialized Alfa {alfa_id} with ranks: {', '.join(ranks_created) if ranks_created else 'core only'}")
    return 0


def _enforce_batch_limit(config: Dict[str, Any], count: int, override: bool) -> bool:
    limit = config.get("safety", {}).get("max_alfa_per_batch")
    if limit is None:
        return True
    if count <= limit:
        return True
    if override:
        print(
            f"[forge] override enabled — processing {count} targets despite limit of {limit}",
            file=sys.stderr,
        )
        return True
    print(f"[forge] batch exceeds limit ({count} > {limit}). Use --override to proceed.", file=sys.stderr)
    return False


def _hydrate_rank(alfa_dir: Path, context: Dict[str, Any], rank_name: str) -> None:
    template_path = f"ranks/{rank_name}.json.j2"
    rendered_rank = render_template(template_path, context)
    (alfa_dir / f"{rank_name}.json").write_text(rendered_rank, encoding="utf-8")


def command_hydrate(args: argparse.Namespace) -> int:
    config = load_config()
    alfa_root = ensure_alfa_root(config)
    records = list_alfa_records(alfa_root)

    targets: List[Dict[str, Any]]
    if args.id:
        targets = [rec for rec in records if rec["id"] == args.id]
        if not targets:
            print(f"[forge] no Alfa found with id '{args.id}'", file=sys.stderr)
            return 1
    elif args.selector:
        targets = apply_selector(records, args.selector)
        if not targets:
            print("[forge] selector matched no Alfas", file=sys.stderr)
            return 1
    else:
        print("[forge] provide either --id or --selector", file=sys.stderr)
        return 1

    if not _enforce_batch_limit(config, len(targets), args.override):
        return 1

    ranks = args.rank or []
    if not ranks:
        print("[forge] no ranks specified for hydration", file=sys.stderr)
        return 1

    template_version = config.get("default_template_version", "forge-template@1.0.0")
    hydrated: List[str] = []

    for record in targets:
        alfa_dir = Path(record["path"])
        manifest = record.get("manifest") or {}
        context = {
            "alfa_id": record["id"],
            "realm": manifest.get("realm", args.realm),
            "entropy_index": manifest.get("entropy_index", args.entropy),
            "template_version": template_version,
        }
        manifest_path = alfa_dir / "manifest.json"
        manifest_data = json.loads(manifest_path.read_text(encoding="utf-8"))
        for rank_name in ranks:
            try:
                _hydrate_rank(alfa_dir, context, rank_name)
            except TemplateEngineError as exc:
                print(f"[forge] template error for rank '{rank_name}': {exc}", file=sys.stderr)
                return 1
            manifest_data.setdefault("ranks", {})[rank_name] = "ok"
        manifest_path.write_text(json.dumps(manifest_data, indent=2) + "\n", encoding="utf-8")
        hydrated.append(record["id"])

    write_log(
        "hydrate",
        {
            "targets": hydrated,
            "ranks": ranks,
            "selector": args.selector,
        },
    )
    print(f"[forge] hydrated ranks {', '.join(ranks)} for {len(hydrated)} Alfa(s)")
    return 0


def command_diff_plan(args: argparse.Namespace) -> int:
    payload = {
        "target_command": args.target,
        "parameters": vars(args),
    }
    write_log("diff_plan", payload)
    print(
        "[forge] diff-plan placeholder — integrate with template engine to preview changes for",
        args.target,
    )
    return 0


def command_validate(_: argparse.Namespace) -> int:
    issues = []
    if not CONFIG_PATH.exists():
        issues.append("forge.config.json missing")
    template_root = ROOT / "template" / "forge"
    if not template_root.exists():
        issues.append("template/forge directory missing")
    else:
        try:
            render_template("alfa/manifest.json.j2", {"alfa_id": "validation", "realm": "Dayland", "entropy_index": 0.0, "template_version": "test"})
        except (TemplateEngineError, ImportError) as exc:
            issues.append(f"template rendering failed: {exc}")
    if issues:
        for issue in issues:
            print(f"[forge] validation error: {issue}", file=sys.stderr)
        write_log("validate", {"status": "failed", "issues": issues})
        return 1
    write_log("validate", {"status": "passed"})
    print("[forge] validation passed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Forge automation toolkit")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init-alfa", help="Create Alfa from templates")
    init_parser.add_argument("--id", required=True, help="Identifier for the Alfa")
    init_parser.add_argument("--realm", default="Dayland", help="Realm designation for the Alfa")
    init_parser.add_argument("--entropy", type=float, default=0.0, help="Initial entropy index")
    init_parser.add_argument(
        "--activate-rank",
        action="append",
        default=[],
        metavar="RANK",
        help="Instantiate additional rank template (repeatable)",
    )
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing Alfa directory")
    init_parser.set_defaults(func=command_init_alfa)

    hydrate_parser = subparsers.add_parser("hydrate", help="Materialize rank files for existing Alfas")
    hydrate_parser.add_argument("--id", help="Specific Alfa id to hydrate")
    hydrate_parser.add_argument("--selector", help="Selector expression targeting Alfas")
    hydrate_parser.add_argument(
        "--rank",
        action="append",
        metavar="RANK",
        help="Rank template to materialize (repeatable)",
    )
    hydrate_parser.add_argument("--realm", default="Dayland", help="Realm default when manifest missing")
    hydrate_parser.add_argument("--entropy", type=float, default=0.0, help="Entropy default when manifest missing")
    hydrate_parser.add_argument("--override", action="store_true", help="Override batch safety limits")
    hydrate_parser.set_defaults(func=command_hydrate)

    diff_parser = subparsers.add_parser("diff-plan", help="Preview changes for a command")
    diff_parser.add_argument("--target", required=True, help="Command to preview")
    diff_parser.set_defaults(func=command_diff_plan)

    validate_parser = subparsers.add_parser("validate", help="Validate Forge configuration and templates")
    validate_parser.set_defaults(func=command_validate)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
