"""Forge CLI skeleton for Alfa automation."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "forge.config.json"
LOG_PATH = ROOT / "logs" / "forge.log"


def load_config() -> Dict[str, Any]:
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Missing forge config at {CONFIG_PATH}")
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def write_log(event: str, payload: Dict[str, Any]) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "event": event,
        **payload,
    }
    with LOG_PATH.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(entry, ensure_ascii=False) + "\n")


def ensure_alfa_root(config: Dict[str, Any]) -> Path:
    alfa_root = ROOT / config.get("alfa_root", "alfas/")
    alfa_root.mkdir(parents=True, exist_ok=True)
    return alfa_root


def command_init_alfa(args: argparse.Namespace) -> int:
    config = load_config()
    alfa_root = ensure_alfa_root(config)
    alfa_id = args.id
    alfa_dir = alfa_root / alfa_id
    if alfa_dir.exists() and not args.force:
        print(f"[forge] Alfa {alfa_id} already exists at {alfa_dir}", file=sys.stderr)
        return 1
    alfa_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "id": alfa_id,
        "realm": "Dayland",
        "ranks": {"alfa": "ok"},
        "entropy_index": 0.0,
        "last_run": None,
        "version": config.get("default_template_version", "forge-template@1.0.0"),
        "checksums": {},
        "notes": "Skeleton manifest generated by Forge CLI; replace with templated output when renderer is ready.",
    }
    (alfa_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (alfa_dir / "README.md").write_text(
        f"# {alfa_id}\n\nPlaceholder Alfa generated by Forge skeleton. Populate rank files once templates are active.\n",
        encoding="utf-8",
    )

    write_log("init_alfa", {"alfa_id": alfa_id, "path": str(alfa_dir), "force": args.force})
    print(f"[forge] Initialized skeleton Alfa at {alfa_dir}")
    return 0


def command_diff_plan(args: argparse.Namespace) -> int:
    payload = {
        "target_command": args.target,
        "parameters": vars(args),
    }
    write_log("diff_plan", payload)
    print(
        "[forge] diff-plan placeholder — integrate with template engine to preview changes for",
        args.target,
    )
    return 0


def command_validate(_: argparse.Namespace) -> int:
    issues = []
    if not CONFIG_PATH.exists():
        issues.append("forge.config.json missing")
    template_root = ROOT / "template" / "forge"
    if not template_root.exists():
        issues.append("template/forge directory missing")
    if issues:
        for issue in issues:
            print(f"[forge] validation error: {issue}", file=sys.stderr)
        write_log("validate", {"status": "failed", "issues": issues})
        return 1
    write_log("validate", {"status": "passed"})
    print("[forge] validation passed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Forge automation toolkit")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init-alfa", help="Create skeleton Alfa")
    init_parser.add_argument("--id", required=True, help="Identifier for the Alfa")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing Alfa directory")
    init_parser.set_defaults(func=command_init_alfa)

    diff_parser = subparsers.add_parser("diff-plan", help="Preview changes for a command")
    diff_parser.add_argument("--target", required=True, help="Command to preview")
    diff_parser.set_defaults(func=command_diff_plan)

    validate_parser = subparsers.add_parser("validate", help="Validate Forge configuration and templates")
    validate_parser.set_defaults(func=command_validate)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
